### ISSUE TITLE
Simplify: Apply shared properties to multiple selectors at once.

### ISSUE THREAD

**Issue by josephtkim** [johnnykalalua/prj-rev-bwfs-dasmoto#4]
When there are shared styling properties for multiple elements, it is a good idea to simplify the code. For instance, there are a few shared properties like the font-family, which can be simplified like

```css
h2, h3, p, .price {
  font-family: Helvetica;
}
```
